title: Reverse Blog
iconURL: 
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: 
  github: 

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 
google_analytics: 
